In [1]:
import pandas as pd

In [2]:

df = pd.read_csv("club_signups.csv")


print("First 5 rows:")
display(df.head())

First 5 rows:

,signup_id,student_id,full_name,email,faculty,city,club,signed_up_at,fee_paid
0,S015,61-8942,Hana Zaki,hana.zaki@student.guc.edu.eg,Pharmacy,Giza,Soccer,2026-09-15 13:39,N
1,S010,61-3846,AHMED ZAKI,ahmed.zaki@student.guc.edu.eg,Management,alexandria,Chess,15/09/2026 03:12,false
2,S008,61-4844,Mohamed Adel,mohamed.adel@student.guc.edu.eg,EMS,Cairo,Music,2026-09-14 23:32,Y
3,S035,61-4844,MOHAMED ADEL,mohamed.adel@student.guc.edu.eg,Engineering and Materials Science,Cairo,Debating,2026-09-17 11:15,yes
4,S004,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Chess Club,2026-09-13 22:36,yes

# Look First

In [3]:

print("Shape (rows, columns):", df.shape)

print("\nDataFrame Info:")
print(df.info())


print("\nMissing values:")
print(df.isna().sum())

Shape (rows, columns): (39, 9)

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   signup_id     39 non-null     object
 1   student_id    39 non-null     object
 2   full_name     39 non-null     object
 3   email         39 non-null     object
 4   faculty       39 non-null     object
 5   city          39 non-null     object
 6   club          39 non-null     object
 7   signed_up_at  39 non-null     object
 8   fee_paid      39 non-null     object
dtypes: object(9)
memory usage: 2.9+ KB
None

Missing values:
signup_id       0
student_id      0
full_name       0
email           0
faculty         0
city            0
club            0
signed_up_at    0
fee_paid        0
dtype: int64

In [4]:
categorical_cols = ["faculty", "club", "city", "fee_paid"]

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- faculty ---
faculty
Pharmacy                                  7
EMS                                       7
IET                                       5
Management                                4
Information Engineering and Technology    4
MET                                       3
iet                                       3
Engineering and Materials Science         1
Pharma                                    1
met                                       1
Media Engineering and Technology          1
pharmacy                                  1
ems                                       1
Name: count, dtype: int64

--- club ---
club
Robotics       8
Music          5
Chess          4
football       4
Debating       3
Chess Club     3
Football       3
Soccer         2
music          2
chess          2
debate club    1
Music          1
Debate         1
Name: count, dtype: int64

--- city ---
city
Cairo         13
Alexandria    11
Giza           4
Alex           4
cairo          2
giza           2
alexandria     1
CAIRO          1
El Giza        1
Name: count, dtype: int64

--- fee_paid ---
fee_paid
yes      7
1        7
false    6
Y        5
N        4
TRUE     4
Yes      4
0        1
no       1
Name: count, dtype: int64

In [5]:
exact_duplicates = df.duplicated().sum()

print("Exact duplicate rows:", exact_duplicates)

print("\nExact duplicate rows:")
display(df[df.duplicated(keep=False)])

df = df.drop_duplicates().copy()

print("Rows after removing exact duplicates:", len(df))

Exact duplicate rows: 3

Exact duplicate rows:

,signup_id,student_id,full_name,email,faculty,city,club,signed_up_at,fee_paid
0,S015,61-8942,Hana Zaki,hana.zaki@student.guc.edu.eg,Pharmacy,Giza,Soccer,2026-09-15 13:39,N
15,S022,61-8224,Sara Zaki,sara.zaki@student.guc.edu.eg,EMS,giza,Music,2026-09-16 01:39,Y
20,S023,58-1125,Ziad Saleh,ziad.saleh@student.guc.edu.eg,Information Engineering and Technology,Cairo,Chess,2026-09-16 09:29,false
24,S022,61-8224,Sara Zaki,sara.zaki@student.guc.edu.eg,EMS,giza,Music,2026-09-16 01:39,Y
33,S023,58-1125,Ziad Saleh,ziad.saleh@student.guc.edu.eg,Information Engineering and Technology,Cairo,Chess,2026-09-16 09:29,false
34,S015,61-8942,Hana Zaki,hana.zaki@student.guc.edu.eg,Pharmacy,Giza,Soccer,2026-09-15 13:39,N

Rows after removing exact duplicates: 36

In [6]:
# Compare duplicate detection before standardizing club names

duplicates_before_club_cleaning = df.duplicated(
    subset=["student_id", "club"]
).sum()

print(
    "Repeated student + club sign-ups before club cleaning:",
    duplicates_before_club_cleaning
)

Repeated student + club sign-ups before club cleaning: 2

# Faculty, club, city.

In [7]:

print(df["faculty"].value_counts(dropna=False))

faculty
Pharmacy                                  6
EMS                                       6
IET                                       5
Management                                4
MET                                       3
Information Engineering and Technology    3
iet                                       3
Engineering and Materials Science         1
Pharma                                    1
met                                       1
Media Engineering and Technology          1
pharmacy                                  1
ems                                       1
Name: count, dtype: int64

In [8]:
df["faculty"] = df["faculty"].str.strip().str.lower()


faculty_map = {
    "met": "MET",
    "media engineering and technology": "MET",
    "iet": "IET",
    "information engineering and technology": "IET",
    "ems": "EMS",
    "engineering and materials science": "EMS",
    "pharmacy": "Pharmacy",
    "pharma": "Pharmacy",
    "management": "Management"
}

df["faculty"] = df["faculty"].map(faculty_map)


print(df["faculty"].value_counts(dropna=False))

allowed_faculties = {"MET", "IET", "EMS", "Pharmacy", "Management"}

assert df["faculty"].notna().all()
assert set(df["faculty"].unique()) == allowed_faculties

faculty
IET           11
Pharmacy       8
EMS            8
MET            5
Management     4
Name: count, dtype: int64

In [9]:
print(df["club"].value_counts(dropna=False))

club
Robotics       8
Music          4
football       4
Chess          3
Debating       3
Chess Club     3
Football       3
music          2
chess          2
Soccer         1
debate club    1
Music          1
Debate         1
Name: count, dtype: int64

In [10]:
club_map = {
    "robotics": "Robotics",
    "music": "Music",
    "chess": "Chess",
    "chess club": "Chess",
    "football": "Football",
    "soccer": "Football",
    "debate": "Debate",
    "debate club": "Debate",
    "debating": "Debate"
}


df["club"] = df["club"].str.strip().str.lower().map(club_map)

print(df["club"].value_counts(dropna=False))

allowed_clubs = {"Robotics", "Debate", "Music", "Football", "Chess"}

assert df["club"].notna().all()
assert set(df["club"].unique()) == allowed_clubs

club
Football    8
Chess       8
Robotics    8
Music       7
Debate      5
Name: count, dtype: int64

In [11]:

print(df["city"].value_counts(dropna=False))

city
Cairo         12
Alexandria    11
Alex           4
Giza           3
cairo          2
alexandria     1
CAIRO          1
giza           1
El Giza        1
Name: count, dtype: int64

In [12]:
df["city"] = df["city"].str.strip().str.lower()


city_map = {
    "cairo": "Cairo",
    "alexandria": "Alexandria",
    "alex": "Alexandria",
    "giza": "Giza",
    "el giza": "Giza"
}

df["city"] = df["city"].map(city_map)

print(df["city"].value_counts(dropna=False))

allowed_cities = {"Cairo", "Giza", "Alexandria"}

assert df["city"].notna().all()
assert set(df["city"].unique()) == allowed_cities

city
Alexandria    16
Cairo         15
Giza           5
Name: count, dtype: int64

# Names and emails

In [13]:
print(df["full_name"].value_counts(dropna=False))

full_name
Laila Mostafa         4
Mohamed Adel          3
Hana Zaki             2
Sara Zaki             2
Youssef Fathy         2
Karim Kamel           2
ali ibrahim           2
Ali Ibrahim           2
Ziad Saleh            2
  Farida  Ibrahim     1
  Laila  Mostafa      1
Salma Ibrahim         1
Mariam Kamel          1
Farida Ibrahim        1
  Omar  Adel          1
mohamed adel          1
AHMED ZAKI            1
AHMED ADEL            1
OMAR ADEL             1
ahmed adel            1
ALI IBRAHIM           1
MOHAMED ADEL          1
  Mohamed  Adel       1
laila mostafa         1
Name: count, dtype: int64

In [14]:
df["full_name"] = (
    df["full_name"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.title()
)

In [15]:
print(df["full_name"].value_counts(dropna=False))

full_name
Mohamed Adel      6
Laila Mostafa     6
Ali Ibrahim       5
Hana Zaki         2
Ahmed Adel        2
Omar Adel         2
Ziad Saleh        2
Sara Zaki         2
Farida Ibrahim    2
Karim Kamel       2
Youssef Fathy     2
Ahmed Zaki        1
Mariam Kamel      1
Salma Ibrahim     1
Name: count, dtype: int64

In [16]:
print(df["email"].value_counts(dropna=False))

email
ali.ibrahim@student.guc.edu.eg       5
mohamed.adel@student.guc.edu.eg      4
laila.mostafa@student.guc.edu.eg     4
hana.zaki@student.guc.edu.eg         2
ziad.saleh@student.guc.edu.eg        2
karim.kamel@student.guc.edu.eg       2
LAILA.MOSTAFA@STUDENT.GUC.EDU.EG     2
farida.ibrahim@student.guc.edu.eg    2
sara.zaki@student.guc.edu.eg         2
omar.adel@student.guc.edu.eg         2
youssef.fathy@student.guc.edu.eg     2
ahmed.zaki@student.guc.edu.eg        1
ahmed.adel@student.guc.edu.eg        1
mariam.kamel@student.guc.edu.eg      1
salma.ibrahim@student.guc.edu.eg     1
MOHAMED.ADEL@STUDENT.GUC.EDU.EG      1
 mohamed.adel@student.guc.edu.eg     1
AHMED.ADEL@STUDENT.GUC.EDU.EG        1
Name: count, dtype: int64

In [17]:
df["email"] = df["email"].str.strip().str.lower()

In [18]:
print(df["email"].value_counts(dropna=False))

email
mohamed.adel@student.guc.edu.eg      6
laila.mostafa@student.guc.edu.eg     6
ali.ibrahim@student.guc.edu.eg       5
hana.zaki@student.guc.edu.eg         2
ahmed.adel@student.guc.edu.eg        2
omar.adel@student.guc.edu.eg         2
ziad.saleh@student.guc.edu.eg        2
sara.zaki@student.guc.edu.eg         2
farida.ibrahim@student.guc.edu.eg    2
karim.kamel@student.guc.edu.eg       2
youssef.fathy@student.guc.edu.eg     2
ahmed.zaki@student.guc.edu.eg        1
mariam.kamel@student.guc.edu.eg      1
salma.ibrahim@student.guc.edu.eg     1
Name: count, dtype: int64

# fee paid to boolean

In [19]:

print(df["fee_paid"].value_counts(dropna=False))

fee_paid
yes      7
1        7
false    5
Y        4
TRUE     4
Yes      4
N        3
0        1
no       1
Name: count, dtype: int64

In [20]:

df["fee_paid"] = df["fee_paid"].astype(str).str.strip().str.lower()

fee_map = {
    "yes": True,
    "y": True,
    "true": True,
    "1": True,
    "no": False,
    "n": False,
    "false": False,
    "0": False
}

df["fee_paid"] = df["fee_paid"].map(fee_map)


print(df["fee_paid"].value_counts(dropna=False))
print("\nData type:", df["fee_paid"].dtype)

assert df["fee_paid"].notna().all()
assert df["fee_paid"].map(lambda x: isinstance(x, bool)).all()

fee_paid
True     26
False    10
Name: count, dtype: int64

Data type: bool

# Date Time

In [21]:
print(df["signed_up_at"].value_counts())

signed_up_at
2026-09-15 13:39    1
15/09/2026 03:12    1
2026-09-16 09:29    1
2026-09-17 23:36    1
16/09/2026 01:15    1
2026-09-15 01:05    1
16/09/2026 02:01    1
17/09/2026 12:27    1
15/09/2026 17:20    1
15/09/2026 20:20    1
15/09/2026 18:40    1
15/09/2026 03:28    1
2026-09-15 11:36    1
2026-09-17 23:29    1
15/09/2026 18:01    1
2026-09-17 06:54    1
2026-09-15 05:43    1
2026-09-17 17:14    1
2026-09-16 16:16    1
2026-09-13 14:36    1
2026-09-15 23:07    1
2026-09-14 23:32    1
2026-09-17 11:15    1
2026-09-13 22:36    1
15/09/2026 03:42    1
2026-09-14 17:03    1
2026-09-13 23:52    1
2026-09-16 09:07    1
2026-09-17 00:41    1
2026-09-13 21:16    1
14/09/2026 01:22    1
16/09/2026 23:55    1
2026-09-16 20:31    1
13/09/2026 15:38    1
2026-09-16 01:39    1
18/09/2026 23:36    1
Name: count, dtype: int64

In [22]:
print(df["signed_up_at"].unique())

['2026-09-15 13:39' '15/09/2026 03:12' '2026-09-14 23:32'
 '2026-09-17 11:15' '2026-09-13 22:36' '15/09/2026 03:42'
 '2026-09-14 17:03' '2026-09-13 23:52' '2026-09-15 23:07'
 '2026-09-16 09:07' '2026-09-13 21:16' '14/09/2026 01:22'
 '16/09/2026 23:55' '2026-09-16 20:31' '13/09/2026 15:38'
 '2026-09-16 01:39' '2026-09-17 00:41' '2026-09-13 14:36'
 '2026-09-16 16:16' '2026-09-17 17:14' '2026-09-16 09:29'
 '2026-09-17 23:36' '16/09/2026 01:15' '2026-09-15 01:05'
 '16/09/2026 02:01' '17/09/2026 12:27' '15/09/2026 17:20'
 '15/09/2026 20:20' '15/09/2026 18:40' '15/09/2026 03:28'
 '2026-09-15 11:36' '2026-09-17 23:29' '15/09/2026 18:01'
 '2026-09-17 06:54' '2026-09-15 05:43' '18/09/2026 23:36']

In [23]:

format1 = df["signed_up_at"].str.match(r"\d{4}-\d{2}-\d{2}")
format2 = df["signed_up_at"].str.match(r"\d{2}/\d{2}/\d{4}")


df.loc[format1, "signed_up_at"] = pd.to_datetime(
    df.loc[format1, "signed_up_at"],
    format="%Y-%m-%d %H:%M"
)

df.loc[format2, "signed_up_at"] = pd.to_datetime(
    df.loc[format2, "signed_up_at"],
    format="%d/%m/%Y %H:%M"
)

df["signed_up_at"] = pd.to_datetime(df["signed_up_at"])

print(df["signed_up_at"].head())
print("\nData type:", df["signed_up_at"].dtype)

0   2026-09-15 13:39:00
1   2026-09-15 03:12:00
2   2026-09-14 23:32:00
3   2026-09-17 11:15:00
4   2026-09-13 22:36:00
Name: signed_up_at, dtype: datetime64[ns]

Data type: datetime64[ns]

In [24]:
print(df["signed_up_at"].unique())

<DatetimeArray>
['2026-09-15 13:39:00', '2026-09-15 03:12:00', '2026-09-14 23:32:00',
 '2026-09-17 11:15:00', '2026-09-13 22:36:00', '2026-09-15 03:42:00',
 '2026-09-14 17:03:00', '2026-09-13 23:52:00', '2026-09-15 23:07:00',
 '2026-09-16 09:07:00', '2026-09-13 21:16:00', '2026-09-14 01:22:00',
 '2026-09-16 23:55:00', '2026-09-16 20:31:00', '2026-09-13 15:38:00',
 '2026-09-16 01:39:00', '2026-09-17 00:41:00', '2026-09-13 14:36:00',
 '2026-09-16 16:16:00', '2026-09-17 17:14:00', '2026-09-16 09:29:00',
 '2026-09-17 23:36:00', '2026-09-16 01:15:00', '2026-09-15 01:05:00',
 '2026-09-16 02:01:00', '2026-09-17 12:27:00', '2026-09-15 17:20:00',
 '2026-09-15 20:20:00', '2026-09-15 18:40:00', '2026-09-15 03:28:00',
 '2026-09-15 11:36:00', '2026-09-17 23:29:00', '2026-09-15 18:01:00',
 '2026-09-17 06:54:00', '2026-09-15 05:43:00', '2026-09-18 23:36:00']
Length: 36, dtype: datetime64[ns]

# Duplicates

In [25]:
exact_duplicates = df.duplicated().sum()
print("Exact duplicate rows:", exact_duplicates)

print("\nExact duplicate rows:")
display(df[df.duplicated(keep=False)])

Exact duplicate rows: 0

Exact duplicate rows:

Empty DataFrame
Columns: [signup_id, student_id, full_name, email, faculty, city, club, signed_up_at, fee_paid]
Index: []

Exact duplicates were removed before any normilsation and turns out they were the only ones

In [26]:
duplicates_after_club_cleaning = df.duplicated(
    subset=["student_id", "club"]
).sum()

print(
    "Repeated student + club sign-ups after club cleaning:",
    duplicates_after_club_cleaning
)

print(
    "Additional duplicates found because of club standardization:",
    duplicates_after_club_cleaning - duplicates_before_club_cleaning
)

duplicate_pairs = df[
    df.duplicated(
        subset=["student_id", "club"],
        keep=False
    )
].sort_values(
    ["student_id", "club", "signed_up_at"]
)

display(duplicate_pairs)

Repeated student + club sign-ups after club cleaning: 4
Additional duplicates found because of club standardization: 2

,signup_id,student_id,full_name,email,faculty,city,club,signed_up_at,fee_paid
8,S020,55-9245,Ali Ibrahim,ali.ibrahim@student.guc.edu.eg,MET,Cairo,Music,2026-09-15 23:07:00,False
9,S033,55-9245,Ali Ibrahim,ali.ibrahim@student.guc.edu.eg,MET,Cairo,Music,2026-09-16 09:07:00,True
22,S021,61-4844,Mohamed Adel,mohamed.adel@student.guc.edu.eg,EMS,Cairo,Debate,2026-09-16 01:15:00,False
3,S035,61-4844,Mohamed Adel,mohamed.adel@student.guc.edu.eg,EMS,Cairo,Debate,2026-09-17 11:15:00,True
35,S017,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Debate,2026-09-15 18:01:00,False
25,S034,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Debate,2026-09-16 02:01:00,True
21,S032,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Football,2026-09-17 23:36:00,False
38,S036,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Football,2026-09-18 23:36:00,True

In [27]:
before_repeat_removal = len(df)

df = (
    df.sort_values("signed_up_at")
      .drop_duplicates(
          subset=["student_id", "club"],
          keep="last"
      )
      .copy()
)

repeated_removed = before_repeat_removal - len(df)

print("Repeated sign-ups removed:", repeated_removed)
print("Rows remaining:", len(df))

assert not df.duplicated(
    subset=["student_id", "club"]
).any()

print("Check passed: student_id + club is unique.")

Repeated sign-ups removed: 4
Rows remaining: 32
Check passed: student_id + club is unique.

In [28]:
assert not df.duplicated(
    subset=["student_id", "club"]
).any()

print("Check passed: student_id + club is unique.")

Check passed: student_id + club is unique.

In [29]:
assert set(df["faculty"].unique()) == {
    "MET", "IET", "EMS", "Pharmacy", "Management"
}

assert set(df["club"].unique()) == {
    "Robotics", "Debate", "Music", "Football", "Chess"
}

assert set(df["city"].unique()) == {
    "Cairo", "Giza", "Alexandria"
}

assert df["fee_paid"].dtype == bool

assert pd.api.types.is_datetime64_any_dtype(df["signed_up_at"])

print("All cleaning checks passed.")

All cleaning checks passed.

In [30]:
df.to_csv("club_signups_clean.csv", index=False)

print("Final shape:", df.shape)
print("Saved club_signups_clean.csv")

Final shape: (32, 9)
Saved club_signups_clean.csv